package SETA;

import SETA.Taxi.GridCell;
import Utils.GridHelper;

import java.util.Random;

// Represents a ride request form a user generated by SETA
public class RideRequest
{
    public final int ID;
    public final GridCell startingPos;
    public GridCell destinationPos;

    public RideRequest()
    {
        // Unique ID between 0 and 100000
        ID = new Random().nextInt(100000);
        startingPos = GridHelper.getRandomPosition();
        destinationPos = startingPos;
        while (destinationPos.equals(startingPos))
            destinationPos = GridHelper.getRandomPosition();
    }

    public double getKm (){
        return GridHelper.getDistance(startingPos, destinationPos);
    }

    public String toString()
    {
        return "Ride request ID " + ID + " from " + startingPos + " to " + destinationPos +
                ". [district " + GridHelper.getDistrict(startingPos) + "]";
    }
}
